module.exports = {
  env: {
    browser: true,
    node: true,
    es2020: true,
  },

  parserOptions: {
    ecmaVersion: 11,
    sourceType: "module",
    requireConfigFile: false,
  },

  rules: {
    "no-cond-assign": 2,
    "no-console": 1,
    "no-debugger": 2,
    "no-irregular-whitespace": 2,
    "no-unexpected-multiline": 2,
    "no-unsafe-negation": 2,
    "valid-jsdoc": [
      2,
      {
        requireParamDescription: false,
        requireReturn: false,
        prefer: { returns: "return" },
      },
    ],
    "class-methods-use-this": [
      2,
      {
        exceptMethods: [
          "constructor",
          "componentWillMount",
          "render",
          "componentDidMount",
          "componentWillReceiveProps",
          "shouldComponentUpdate",
          "componentWillUpdate",
          "render",
          "componentDidUpdate",
          "componentWillUnmount",
          "componentDidCatch",
        ],
      },
    ],
    curly: ['error', 'all'],
    "default-case": 2,
    "dot-notation": 2,
    eqeqeq: 2,
    "guard-for-in": 2,
    "no-alert": 1,
    "no-caller": 2,
    "no-empty-function": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-global-assign": 2,
    "no-invalid-this": 0,
    "no-labels": 2,
    "no-loop-func": 2,
    "no-multi-spaces": 2,
    "no-multi-str": 2,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-new": 2,
    "no-return-assign": 0,
    "no-throw-literal": 2,
    "no-unmodified-loop-condition": 2,
    "no-useless-concat": 2,
    "no-void": 2,
    "no-warning-comments": 1,
    "no-with": 2,
    radix: [2, "as-needed"],
    "no-shadow": 0,
    "no-undef": 2,
    "no-undefined": 2,
    "no-unused-vars": [2, { args: "after-used" }],
    "no-use-before-define": 2,
    "array-bracket-spacing": [2, "never"],
    "brace-style": 2,
    camelcase: 2,
    "comma-dangle": [2, "always-multiline"],
    "comma-spacing": 2,
    "comma-style": 2,
    "computed-property-spacing": 2,
    "consistent-this": 2,
    "eol-last": 2,
    "func-call-spacing": 2,
    indent: [2, 2, { SwitchCase: 1 }],
    "key-spacing": 2,
    "keyword-spacing": 2,
    "linebreak-style": 2,
    "max-len": [
      2,
      {
        code: 120,
        tabWidth: 2,
        ignoreComments: true,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      },
    ],
    "new-cap": 0,
    "new-parens": 2,
    "no-array-constructor": 2,
    "no-lonely-if": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-multiple-empty-lines": [2, { max: 2 }],
    "no-nested-ternary": 2,
    "no-new-object": 2,
    "no-trailing-spaces": 2,
    "no-unneeded-ternary": 2,
    "no-whitespace-before-property": 2,
    "object-curly-spacing": 0,
    "one-var": [
      2,
      {
        var: "never",
        let: "never",
        const: "never",
      },
    ],
    "operator-linebreak": [2, "after"],
    "padded-blocks": [2, "never"],
    "quote-props": [2, "as-needed"],
    quotes: [2, "single", { allowTemplateLiterals: true }],
    semi: [2, "always"],
    "semi-spacing": 2,
    "space-before-blocks": 2,
    "space-before-function-paren": [
      2,
      {
        anonymous: "never",
        named: "never",
        asyncArrow: "always",
      },
    ],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "spaced-comment": [2, "always"],
    "arrow-body-style": [2, "as-needed"],
    "arrow-parens": [2, "as-needed"],
    "arrow-spacing": 2,
    "constructor-super": 2,
    "generator-star-spacing": [2, "before"],
    "no-duplicate-imports": 2,
    "no-new-symbol": 2,
    "no-this-before-super": 2,
    "no-useless-constructor": 2,
    "no-var": 2,
    "object-shorthand": [2, "always"],
    "prefer-const": 2,
    "prefer-rest-params": 2,
    "prefer-spread": 2,
    "prefer-template": 2,
    "rest-spread-spacing": 2,
    "yield-star-spacing": [2, "before"],
  },
};
